development:
  auth0_domain: <%= Rails.application.credentials.dig(:auth0, :development, :domain) %>
  auth0_client_id: <%= Rails.application.credentials.dig(:auth0, :development, :client_id) %>
  auth0_client_secret: <%= Rails.application.credentials.dig(:auth0, :development, :client_secret) %>

production:
  auth0_domain: <%= Rails.application.credentials.dig(:auth0, :production, :domain) %>
  auth0_client_id: <%= Rails.application.credentials.dig(:auth0, :production, :client_id) %>
  auth0_client_secret: <%= Rails.application.credentials.dig(:auth0, :production, :client_secret) %>
