development:
  auth0_domain: <%= Rails.application.credentials.dig(:auth0, :domain) %>
  auth0_client_id: <%= Rails.application.credentials.dig(:auth0, :client_id) %>
  auth0_client_secret: <%= Rails.application.credentials.dig(:auth0, :client_secret) %>
